### ISSUE TITLE
Project Overview

### ISSUE THREAD

**Issue by hmontero1205** [Slushnas/Tome-Rater#1]
## Rubric Score
 
### Criteria 1: Valid Python Code
* _Score Level:_ 4
 
### Criteria 2: Implementation of Project Requirements
* _Score Level:_ 4
 
### Criteria 3: Software Architecture
* _Score Level:_ 4
 
### Criteria 4: Uses Python Language Features
* _Score Level:_ 4
 
### Overall Score: 16/16
Your work definitely meets the project requirements -- awesome work!! You demonstrate an excellent understanding of Python. I really like that you used `assert`! You even checked if the other object is an instance of the same class in your `eq` method!!!I am really confident that you will be able to apply these skills to your future endeavors. :)

Just one thing -- what if the length of `self.ratings` is 0?

Good luck!

**Comment by Slushnas** [comment]
Thanks for the kind words! Also, good catch with the divide by zero error when `self.ratings` is empty. I've fixed that issue in the code.

Thanks again for the review!
